spring.application.name=shortener

spring.datasource.url=jdbc:mysql://localhost:3306/urlshortenerdb
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true


jwt.secret=Y9DmEelY221nMO9bcM4O3n8KfYzdmOOxhGnFcPT4VXG
jwt.expiration=172800000

frontend.url=http://localhost:5173